CSHTGT.WebUser/Models/ErrorViewModel.cs
using System;

namespace CSHTGT.WebUser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSHTGT.WebUser/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CSHTGT.WebUser.Models;

namespace CSHTGT.WebUser.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSHTGT.WebUser/Controllers/PhieuDangKyThuTucController.cs
using CSHTGT.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CSHTGT.WebUser.Controllers
{
    public class PhieuDangKyThuTucController : Controller
    {
        public async Task<IActionResult> Index()
        {
            List<PhieuDangKyThuTucViewModel> listPhieuDangKy = new List<PhieuDangKyThuTucViewModel>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:5001/api/PhieuDangKyThuTuc"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    listPhieuDangKy = JsonConvert.DeserializeObject<List<PhieuDangKyThuTucViewModel>>(apiResponse);
                }
            }
            return View(listPhieuDangKy);
        }

        public IActionResult AddPhieuDangKyThuTuc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddPhieuDangKyThuTUc(PhieuDangKyThuTucViewModel phieuDangKyThuTucViewModel)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:5001/");
            var postTask = client.PostAsJsonAsync<PhieuDangKyThuTucViewModel>("api/phieudangkythutuc", phieuDangKyThuTucViewModel);
            postTask.Wait();
            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                TempData["result"] = "Đăng kí lịch hẹn thành công";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Đăng kí lịch hẹn thất bại");
            return View(phieuDangKyThuTucViewModel);
        }
    }
}

CSHTGT.WebUser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CSHTGT.WebUser/Views/PhieuDangKyThuTuc/AddPhieuDangKyThuTuc.cshtml
@model CSHTGT.ViewModels.PhieuDangKyThuTucViewModel


@{
    ViewData["Title"] = "Đăng kí lịch hẹn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <h1 class="mt-4">Đăng kí lịch hẹn</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/Home">Trang chủ</a></li>

        <li class="breadcrumb-item ">Đăng kí lịch hẹn</li>
    </ol>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AddPhieuDangKyThuTuc">
                <div class="form-group">
                    <a class="btn btn-primary" asp-action="Index" asp-controller="PhieuDangKyThuTuc">Trở về danh sách đăng kí</a>
                </div>
                <h5>Nhập thông tin phương tiện</h5>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <label asp-for="MaNgTGGiaoThong" class="control-label">Mã Người Tham Gia Giao Thông</label>
                    <input asp-for="MaNgTGGiaoThong" class="form-control" placeholder="1"/>
                    <span asp-validation-for="MaNgTGGiaoThong" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="TenPT" class="control-label">Tên phương tiện(*)</label>
                    <input asp-for="TenPT" class="form-control" />
                    <span asp-validation-for="TenPT" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BienSo" class="control-label">Biển số(*)</label>
                    <input asp-for="BienSo" class="form-control" />
                    <span asp-validation-for="BienSo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NhanHieu" class="control-label">Nhãn hiệu(*)</label>
                    <input asp-for="NhanHieu" class="form-control" />
                    <span asp-validation-for="NhanHieu" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SoChoNgoi" class="control-label">Số chỗ ngồi</label>
                    <input asp-for="SoChoNgoi" class="form-control" />
                    <span asp-validation-for="SoChoNgoi" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SoKhung" class="control-label">Số khung</label>
                    <input asp-for="SoKhung" class="form-control" />
                    <span asp-validation-for="SoKhung" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SoMay" class="control-label">Số máy</label>
                    <input asp-for="SoMay" class="form-control" />
                    <span asp-validation-for="SoMay" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LoaiDangKy" class="control-label">Loại Đăng Ký</label>
                    <select name="LoaiDangKy" class="form-control">
                        <option>Cấp Cà Vạt Xe</option>
                        <option>Cấp Mới Cà Vạt Xe</option>
                        <option>Sang Tên Xe</option>
                        <option>Thu Hồi Xe</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="NgayDangKy" class="control-label">Ngày Đăng Ký</label>
                    <input asp-for="NgayDangKy" class="form-control" />
                    <span asp-validation-for="SoMay" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Đăng kí" class="btn btn-primary" />
                </div>

            </form>


        </div>
    </div>
</div>

CSHTGT.WebUser/Views/PhieuDangKyThuTuc/Index.cshtml
@model IEnumerable<CSHTGT.ViewModels.PhieuDangKyThuTucViewModel>

@{ ViewData["Title"] = "Danh sách lịch hẹn đã đặt";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="container-fluid">
    <h1 class="mt-4">Danh sách lịch hẹn</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/Home">Trang chủ</a></li>
        <li class="breadcrumb-item">Danh sách lịch hẹn</li>
    </ol>
    <p>
        <div class="form-group">
            <a class="btn btn-primary" asp-action="AddPhieuDangKyThuTuc" asp-controller="PhieuDangKyThuTuc">Tạo mới</a>
        </div>
    </p>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        Tên phương tiện
                    </th>
                    <th>
                        Biển số
                    </th>
                    <th>
                        Nhãn hiệu
                    </th>
                    <th>
                        Số chỗ ngồi
                    </th>
                    <th>
                        Số khung
                    </th>
                    <th>
                        Số máy
                    </th>
                    <th>
                        Loại Đăng Ký
                    </th>
                    <th>
                        Trạng Thái
                    </th>
                    <th>
                        Ngày Đăng Ký
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenPT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BienSo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanHieu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoChoNgoi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoKhung)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoMay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiDangKy)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.XetDuyet)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayDangKy)

                    </td>
                </tr>
}
            </tbody>
        </table>
    </div>

</div>

CSHTGT.WebUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] </title>
    <link href="/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/Home">Ứng Dụng Giao Thông</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="/Home">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Trang chủ
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Đăng Ký Dịch Vụ
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="/PhieuDangKyThuTuc/AddPhieuDangKyThuTuc">Cấp Cà Vạt Xe</a>
                                <a class="nav-link" href="/PhieuDangKyThuTuc/AddPhieuDangKyThuTuc">Cấp Mới Cà Vạt Xe</a>
                                <a class="nav-link" href="/PhieuDangKyThuTuc/AddPhieuDangKyThuTuc">Sang Tên Xe</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Đăng nhập bằng:</div>
                    Phát triển UD HTTT Hiện đại
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Phát triển ứng dụng HTTT Hiện đại 2020</div>
                        <div>
                            <a href="#">Chính sách bảo mật</a>
                            &middot;
                            <a href="#">Điều khoản</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="/assets/demo/datatables-demo.js"></script>
</body>
</html>